/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class fields extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2591234697396570204L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"fields\",\"fields\":[{\"name\":\"key_field1\",\"type\":\"string\"},{\"name\":\"timestamp_field1\",\"type\":\"string\"},{\"name\":\"string_field1\",\"type\":\"string\"},{\"name\":\"double_field1\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<fields> ENCODER =
      new BinaryMessageEncoder<fields>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<fields> DECODER =
      new BinaryMessageDecoder<fields>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<fields> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<fields> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<fields> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<fields>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this fields to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a fields from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a fields instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static fields fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence key_field1;
  private java.lang.CharSequence timestamp_field1;
  private java.lang.CharSequence string_field1;
  private java.lang.CharSequence double_field1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public fields() {}

  /**
   * All-args constructor.
   * @param key_field1 The new value for key_field1
   * @param timestamp_field1 The new value for timestamp_field1
   * @param string_field1 The new value for string_field1
   * @param double_field1 The new value for double_field1
   */
  public fields(java.lang.CharSequence key_field1, java.lang.CharSequence timestamp_field1, java.lang.CharSequence string_field1, java.lang.CharSequence double_field1) {
    this.key_field1 = key_field1;
    this.timestamp_field1 = timestamp_field1;
    this.string_field1 = string_field1;
    this.double_field1 = double_field1;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key_field1;
    case 1: return timestamp_field1;
    case 2: return string_field1;
    case 3: return double_field1;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key_field1 = (java.lang.CharSequence)value$; break;
    case 1: timestamp_field1 = (java.lang.CharSequence)value$; break;
    case 2: string_field1 = (java.lang.CharSequence)value$; break;
    case 3: double_field1 = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'key_field1' field.
   * @return The value of the 'key_field1' field.
   */
  public java.lang.CharSequence getKeyField1() {
    return key_field1;
  }


  /**
   * Sets the value of the 'key_field1' field.
   * @param value the value to set.
   */
  public void setKeyField1(java.lang.CharSequence value) {
    this.key_field1 = value;
  }

  /**
   * Gets the value of the 'timestamp_field1' field.
   * @return The value of the 'timestamp_field1' field.
   */
  public java.lang.CharSequence getTimestampField1() {
    return timestamp_field1;
  }


  /**
   * Sets the value of the 'timestamp_field1' field.
   * @param value the value to set.
   */
  public void setTimestampField1(java.lang.CharSequence value) {
    this.timestamp_field1 = value;
  }

  /**
   * Gets the value of the 'string_field1' field.
   * @return The value of the 'string_field1' field.
   */
  public java.lang.CharSequence getStringField1() {
    return string_field1;
  }


  /**
   * Sets the value of the 'string_field1' field.
   * @param value the value to set.
   */
  public void setStringField1(java.lang.CharSequence value) {
    this.string_field1 = value;
  }

  /**
   * Gets the value of the 'double_field1' field.
   * @return The value of the 'double_field1' field.
   */
  public java.lang.CharSequence getDoubleField1() {
    return double_field1;
  }


  /**
   * Sets the value of the 'double_field1' field.
   * @param value the value to set.
   */
  public void setDoubleField1(java.lang.CharSequence value) {
    this.double_field1 = value;
  }

  /**
   * Creates a new fields RecordBuilder.
   * @return A new fields RecordBuilder
   */
  public static fields.Builder newBuilder() {
    return new fields.Builder();
  }

  /**
   * Creates a new fields RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new fields RecordBuilder
   */
  public static fields.Builder newBuilder(fields.Builder other) {
    if (other == null) {
      return new fields.Builder();
    } else {
      return new fields.Builder(other);
    }
  }

  /**
   * Creates a new fields RecordBuilder by copying an existing fields instance.
   * @param other The existing instance to copy.
   * @return A new fields RecordBuilder
   */
  public static fields.Builder newBuilder(fields other) {
    if (other == null) {
      return new fields.Builder();
    } else {
      return new fields.Builder(other);
    }
  }

  /**
   * RecordBuilder for fields instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<fields>
    implements org.apache.avro.data.RecordBuilder<fields> {

    private java.lang.CharSequence key_field1;
    private java.lang.CharSequence timestamp_field1;
    private java.lang.CharSequence string_field1;
    private java.lang.CharSequence double_field1;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(fields.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.key_field1)) {
        this.key_field1 = data().deepCopy(fields()[0].schema(), other.key_field1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp_field1)) {
        this.timestamp_field1 = data().deepCopy(fields()[1].schema(), other.timestamp_field1);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.string_field1)) {
        this.string_field1 = data().deepCopy(fields()[2].schema(), other.string_field1);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.double_field1)) {
        this.double_field1 = data().deepCopy(fields()[3].schema(), other.double_field1);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing fields instance
     * @param other The existing instance to copy.
     */
    private Builder(fields other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.key_field1)) {
        this.key_field1 = data().deepCopy(fields()[0].schema(), other.key_field1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp_field1)) {
        this.timestamp_field1 = data().deepCopy(fields()[1].schema(), other.timestamp_field1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.string_field1)) {
        this.string_field1 = data().deepCopy(fields()[2].schema(), other.string_field1);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.double_field1)) {
        this.double_field1 = data().deepCopy(fields()[3].schema(), other.double_field1);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'key_field1' field.
      * @return The value.
      */
    public java.lang.CharSequence getKeyField1() {
      return key_field1;
    }


    /**
      * Sets the value of the 'key_field1' field.
      * @param value The value of 'key_field1'.
      * @return This builder.
      */
    public fields.Builder setKeyField1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.key_field1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'key_field1' field has been set.
      * @return True if the 'key_field1' field has been set, false otherwise.
      */
    public boolean hasKeyField1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'key_field1' field.
      * @return This builder.
      */
    public fields.Builder clearKeyField1() {
      key_field1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp_field1' field.
      * @return The value.
      */
    public java.lang.CharSequence getTimestampField1() {
      return timestamp_field1;
    }


    /**
      * Sets the value of the 'timestamp_field1' field.
      * @param value The value of 'timestamp_field1'.
      * @return This builder.
      */
    public fields.Builder setTimestampField1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.timestamp_field1 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp_field1' field has been set.
      * @return True if the 'timestamp_field1' field has been set, false otherwise.
      */
    public boolean hasTimestampField1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp_field1' field.
      * @return This builder.
      */
    public fields.Builder clearTimestampField1() {
      timestamp_field1 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'string_field1' field.
      * @return The value.
      */
    public java.lang.CharSequence getStringField1() {
      return string_field1;
    }


    /**
      * Sets the value of the 'string_field1' field.
      * @param value The value of 'string_field1'.
      * @return This builder.
      */
    public fields.Builder setStringField1(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.string_field1 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'string_field1' field has been set.
      * @return True if the 'string_field1' field has been set, false otherwise.
      */
    public boolean hasStringField1() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'string_field1' field.
      * @return This builder.
      */
    public fields.Builder clearStringField1() {
      string_field1 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'double_field1' field.
      * @return The value.
      */
    public java.lang.CharSequence getDoubleField1() {
      return double_field1;
    }


    /**
      * Sets the value of the 'double_field1' field.
      * @param value The value of 'double_field1'.
      * @return This builder.
      */
    public fields.Builder setDoubleField1(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.double_field1 = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'double_field1' field has been set.
      * @return True if the 'double_field1' field has been set, false otherwise.
      */
    public boolean hasDoubleField1() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'double_field1' field.
      * @return This builder.
      */
    public fields.Builder clearDoubleField1() {
      double_field1 = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public fields build() {
      try {
        fields record = new fields();
        record.key_field1 = fieldSetFlags()[0] ? this.key_field1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp_field1 = fieldSetFlags()[1] ? this.timestamp_field1 : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.string_field1 = fieldSetFlags()[2] ? this.string_field1 : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.double_field1 = fieldSetFlags()[3] ? this.double_field1 : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<fields>
    WRITER$ = (org.apache.avro.io.DatumWriter<fields>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<fields>
    READER$ = (org.apache.avro.io.DatumReader<fields>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.key_field1);

    out.writeString(this.timestamp_field1);

    out.writeString(this.string_field1);

    out.writeString(this.double_field1);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.key_field1 = in.readString(this.key_field1 instanceof Utf8 ? (Utf8)this.key_field1 : null);

      this.timestamp_field1 = in.readString(this.timestamp_field1 instanceof Utf8 ? (Utf8)this.timestamp_field1 : null);

      this.string_field1 = in.readString(this.string_field1 instanceof Utf8 ? (Utf8)this.string_field1 : null);

      this.double_field1 = in.readString(this.double_field1 instanceof Utf8 ? (Utf8)this.double_field1 : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.key_field1 = in.readString(this.key_field1 instanceof Utf8 ? (Utf8)this.key_field1 : null);
          break;

        case 1:
          this.timestamp_field1 = in.readString(this.timestamp_field1 instanceof Utf8 ? (Utf8)this.timestamp_field1 : null);
          break;

        case 2:
          this.string_field1 = in.readString(this.string_field1 instanceof Utf8 ? (Utf8)this.string_field1 : null);
          break;

        case 3:
          this.double_field1 = in.readString(this.double_field1 instanceof Utf8 ? (Utf8)this.double_field1 : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










